USE loja;

ALTER TABLE CLIENTES ADD COLUMN DATA_CADASTRO DATE;

INSERT INTO CLIENTES (ID, DATA_CADASTRO)
VALUES (1, '2022-11-27'), (2, '2022-11-27'), (3, '2022-11-27')
ON DUPLICATE KEY UPDATE DATA_CADASTRO = VALUES(DATA_CADASTRO);

DELIMITER $$
CREATE FUNCTION CADASTROS_DIA (DIA date)
RETURNS INT
DETERMINISTIC
BEGIN 
	DECLARE TOT_CAD int;
	SELECT COUNT(ID) FROM clientes WHERE DATA_CADASTRO = DIA INTO TOT_CAD;
	RETURN TOT_CAD;
END; $$

SELECT CADASTROS_DIA (current_date()) AS CADASTROS_HOJE;


