USE loja;

ALTER TABLE VENDAS ADD COLUMN DATA_VENDA DATE;
UPDATE VENDAS SET DATA_VENDA = '2022-08-12' WHERE ID_VENDA = 1;
UPDATE VENDAS SET DATA_VENDA = '2022-10-01' WHERE ID_VENDA = 2;
UPDATE VENDAS SET DATA_VENDA = '2022-11-27' WHERE ID_VENDA = 3;


CREATE PROCEDURE quant_vendas (dia DATE)
SELECT COUNT(ID_VENDA) AS TOT_VENDAS FROM VENDAS WHERE DATA_VENDA = dia;

CALL quant_vendas(current_date());